NAMES = ['Peanut',
         'Gingerbread',
         'SnickerDoodles',
         'Biscuit',
         'Carrot',
         'ChocolateChip',
         'Macaroon',
         'Wafer',
         'Pancake']
ADJECTIVES = ['Impressive',
              'Amazing',
              'Little',
              'Tiny',
              'Mini',
              'Beautiful',
              'Princess',
              'Queen',
              'Prince',
              'King']